"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { formatKES } from "@/lib/utils/format";
import { formatEnum } from "@/lib/utils/format-enum";
import { Clock, Users, MessageSquare, FileText, Scale } from "lucide-react";
import { APP_LOCALE } from "@/lib/constants/locale";
import { CaseDocumentsTab } from "./case-documents-tab";

interface CaseDetail {
  id: string;
  caseNumber: string;
  title: string;
  status: string;
  priority: string;
  caseType: string;
  practiceArea: string | null;
  billingType: string;
  hourlyRate: string | null;
  flatFeeAmount: string | null;
  contingencyPercentage: string | null;
  courtName: string | null;
  courtCaseNumber: string | null;
  judge: string | null;
  opposingCounsel: string | null;
  opposingParty: string | null;
  statuteOfLimitations: Date | null;
  dateFiled: Date | null;
  estimatedValue: string | null;
  description: string | null;
  notes: string | null;
  clientId: string;
  clientName: string;
  createdAt: Date;
}

interface Assignment {
  id: string;
  role: string;
  assignedAt: Date;
  userName: string | null;
  userId: string;
}

interface Note {
  id: string;
  content: string;
  isPrivate: boolean;
  createdAt: Date;
  authorName: string | null;
}

interface TimelineEvent {
  id: string;
  eventType: string;
  title: string;
  description: string | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  userName: string | null;
}

interface Party {
  id: string;
  name: string;
  role: string;
  email: string | null;
  phone: string | null;
}

interface Doc {
  id: string;
  title: string;
  category: string;
  status: string;
  fileName: string;
  fileSize: number | null;
  fileUrl: string;
  mimeType: string | null;
  createdAt: Date;
  uploadedByName: string | null;
}

interface CaseDetailTabsProps {
  caseData: CaseDetail;
  assignments: Assignment[];
  notes: Note[];
  timeline: TimelineEvent[];
  parties: Party[];
  documents: Doc[];
}

function TabCount({ count }: { count: number }) {
  if (count === 0) return null;
  return (
    <span className="ml-1.5 inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-muted px-1.5 text-[10px] font-semibold tabular-nums">
      {count}
    </span>
  );
}

function DL({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-0.5">
      <dt className="text-xs text-muted-foreground">{label}</dt>
      <dd className="text-sm font-medium">{children}</dd>
    </div>
  );
}

const timelineEventColors: Record<string, string> = {
  status_change: "bg-blue-500",
  note_added: "bg-emerald-500",
  assignment: "bg-purple-500",
  filing: "bg-amber-500",
  hearing: "bg-rose-500",
  document: "bg-cyan-500",
};

export function CaseDetailTabs({
  caseData,
  assignments,
  notes,
  timeline,
  parties,
  documents,
}: CaseDetailTabsProps) {
  return (
    <Tabs defaultValue="details" className="space-y-4">
      <TabsList>
        <TabsTrigger value="details">
          <Scale className="mr-1.5 h-3.5 w-3.5" />
          Details
        </TabsTrigger>
        <TabsTrigger value="documents">
          <FileText className="mr-1.5 h-3.5 w-3.5" />
          Documents
          <TabCount count={documents.length} />
        </TabsTrigger>
        <TabsTrigger value="assignments">
          <Users className="mr-1.5 h-3.5 w-3.5" />
          Assignments
          <TabCount count={assignments.length} />
        </TabsTrigger>
        <TabsTrigger value="parties">
          Parties
          <TabCount count={parties.length} />
        </TabsTrigger>
        <TabsTrigger value="notes">
          <MessageSquare className="mr-1.5 h-3.5 w-3.5" />
          Notes
          <TabCount count={notes.length} />
        </TabsTrigger>
        <TabsTrigger value="timeline">
          <Clock className="mr-1.5 h-3.5 w-3.5" />
          Timeline
        </TabsTrigger>
      </TabsList>

      {/* ── Details ── */}
      <TabsContent value="details">
        <Card>
          <CardContent className="p-6 space-y-6">
            {/* Case Info */}
            <div>
              <h3 className="text-sm font-semibold mb-3">Case Information</h3>
              <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <DL label="Case Type">{formatEnum(caseData.caseType)}</DL>
                {caseData.practiceArea && (
                  <DL label="Practice Area">{caseData.practiceArea}</DL>
                )}
                {caseData.dateFiled && (
                  <DL label="Date Filed">
                    {new Date(caseData.dateFiled).toLocaleDateString(APP_LOCALE)}
                  </DL>
                )}
                {caseData.statuteOfLimitations && (
                  <DL label="Statute of Limitations">
                    {new Date(caseData.statuteOfLimitations).toLocaleDateString(APP_LOCALE)}
                  </DL>
                )}
                {caseData.estimatedValue && (
                  <DL label="Estimated Value">{formatKES(Number(caseData.estimatedValue))}</DL>
                )}
              </dl>
              {caseData.description && (
                <div className="mt-4">
                  <dt className="text-xs text-muted-foreground mb-1">Description</dt>
                  <dd className="text-sm whitespace-pre-wrap leading-relaxed">
                    {caseData.description}
                  </dd>
                </div>
              )}
            </div>

            <Separator />

            {/* Court & Opposition */}
            <div>
              <h3 className="text-sm font-semibold mb-3">Court &amp; Opposition</h3>
              <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <DL label="Court">{caseData.courtName ?? "—"}</DL>
                <DL label="Court Case #">{caseData.courtCaseNumber ?? "—"}</DL>
                <DL label="Judge">{caseData.judge ?? "—"}</DL>
                <DL label="Opposing Party">{caseData.opposingParty ?? "—"}</DL>
                <DL label="Opposing Counsel">{caseData.opposingCounsel ?? "—"}</DL>
              </dl>
            </div>

            <Separator />

            {/* Billing */}
            <div>
              <h3 className="text-sm font-semibold mb-3">Billing</h3>
              <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <DL label="Billing Type">{formatEnum(caseData.billingType)}</DL>
                {caseData.hourlyRate && (
                  <DL label="Hourly Rate">{formatKES(Number(caseData.hourlyRate))}/hr</DL>
                )}
                {caseData.flatFeeAmount && (
                  <DL label="Flat Fee">{formatKES(Number(caseData.flatFeeAmount))}</DL>
                )}
                {caseData.contingencyPercentage && (
                  <DL label="Contingency">{caseData.contingencyPercentage}%</DL>
                )}
              </dl>
            </div>
          </CardContent>
        </Card>
      </TabsContent>

      {/* ── Documents ── */}
      <TabsContent value="documents">
        <CaseDocumentsTab caseId={caseData.id} documents={documents} />
      </TabsContent>

      {/* ── Assignments ── */}
      <TabsContent value="assignments">
        {assignments.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No attorneys assigned.
          </p>
        ) : (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {assignments.map((a) => (
              <Card key={a.id}>
                <CardContent className="flex items-center gap-3 p-4">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">
                    {(a.userName ?? "?").charAt(0).toUpperCase()}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium truncate">{a.userName}</p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <Badge variant="outline" className="text-[10px]">
                        {formatEnum(a.role)}
                      </Badge>
                      <span className="text-[10px] text-muted-foreground">
                        {new Date(a.assignedAt).toLocaleDateString(APP_LOCALE)}
                      </span>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </TabsContent>

      {/* ── Parties ── */}
      <TabsContent value="parties">
        {parties.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No parties added.
          </p>
        ) : (
          <div className="grid gap-3 sm:grid-cols-2">
            {parties.map((p) => (
              <Card key={p.id}>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <p className="text-sm font-medium">{p.name}</p>
                    <Badge variant="outline" className="text-[10px]">
                      {formatEnum(p.role)}
                    </Badge>
                  </div>
                  <div className="space-y-0.5 text-xs text-muted-foreground">
                    {p.email && <p>{p.email}</p>}
                    {p.phone && <p>{p.phone}</p>}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </TabsContent>

      {/* ── Notes ── */}
      <TabsContent value="notes">
        {notes.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No notes added.
          </p>
        ) : (
          <div className="space-y-3">
            {notes.map((n) => (
              <Card key={n.id}>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary">
                      {(n.authorName ?? "?").charAt(0).toUpperCase()}
                    </div>
                    <span className="text-sm font-medium">{n.authorName}</span>
                    <div className="ml-auto flex items-center gap-2">
                      {n.isPrivate && (
                        <Badge variant="secondary" className="text-[10px]">
                          Private
                        </Badge>
                      )}
                      <span className="text-[10px] text-muted-foreground">
                        {new Date(n.createdAt).toLocaleString(APP_LOCALE)}
                      </span>
                    </div>
                  </div>
                  <p className="text-sm whitespace-pre-wrap leading-relaxed pl-9">
                    {n.content}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </TabsContent>

      {/* ── Timeline ── */}
      <TabsContent value="timeline">
        {timeline.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No activity recorded.
          </p>
        ) : (
          <div className="relative ml-3 border-l border-border pl-6 space-y-6">
            {timeline.map((e) => {
              const dotColor =
                timelineEventColors[e.eventType] ?? "bg-muted-foreground";
              return (
                <div key={e.id} className="relative">
                  {/* Dot */}
                  <div
                    className={`absolute -left-[calc(1.5rem+5px)] top-1.5 h-2.5 w-2.5 rounded-full ring-2 ring-background ${dotColor}`}
                  />
                  <div>
                    <p className="text-sm font-medium">{e.title}</p>
                    {e.description && (
                      <p className="text-sm text-muted-foreground mt-0.5">
                        {e.description}
                      </p>
                    )}
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-[10px] text-muted-foreground">
                        {new Date(e.createdAt).toLocaleString(APP_LOCALE)}
                      </span>
                      {e.userName && (
                        <span className="text-[10px] text-muted-foreground">
                          by {e.userName}
                        </span>
                      )}
                      <Badge variant="outline" className="text-[10px]">
                        {formatEnum(e.eventType)}
                      </Badge>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </TabsContent>
    </Tabs>
  );
}
