"use client";

import Link from "next/link";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Progress } from "@/components/ui/progress";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { formatKES } from "@/lib/utils/format";
import { formatEnum } from "@/lib/utils/format-enum";
import { formatRelativeDate } from "@/lib/utils/format";
import { Clock, Users, MessageSquare, FileText, Scale, Receipt, ListTodo, CalendarClock, CircleDollarSign, AlertCircle, CheckCircle2, Timer, ArrowUpRight } from "lucide-react";
import { APP_LOCALE } from "@/lib/constants/locale";
import { CaseDocumentsTab } from "./case-documents-tab";
import { PersonAvatar } from "@/components/shared/person-avatar";
import { InvoiceStatusBadge, TaskStatusBadge, PriorityBadge, BillableBadge } from "@/components/shared/status-badges";
import {
  AddNoteDialog, DeleteNoteButton,
  AddPartyDialog, DeletePartyButton,
  AssignMemberDialog, UnassignButton,
  AddTaskDialog, TaskStatusButton, DeleteTaskButton,
  AddDeadlineDialog, CompleteDeadlineButton, DeleteDeadlineButton,
} from "./case-crud-dialogs";
import { Pencil } from "lucide-react";

interface CaseDetail {
  id: string;
  caseNumber: string;
  title: string;
  status: string;
  priority: string;
  caseType: string;
  practiceArea: string | null;
  billingType: string;
  hourlyRate: string | null;
  flatFeeAmount: string | null;
  contingencyPercentage: string | null;
  courtName: string | null;
  courtCaseNumber: string | null;
  judge: string | null;
  opposingCounsel: string | null;
  opposingParty: string | null;
  statuteOfLimitations: Date | null;
  dateFiled: Date | null;
  estimatedValue: string | null;
  description: string | null;
  notes: string | null;
  clientId: string;
  clientName: string;
  createdAt: Date;
}

interface Assignment {
  id: string;
  role: string;
  assignedAt: Date;
  userName: string | null;
  userId: string;
}

interface Note {
  id: string;
  content: string;
  isPrivate: boolean;
  createdAt: Date;
  authorName: string | null;
}

interface TimelineEvent {
  id: string;
  eventType: string;
  title: string;
  description: string | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  userName: string | null;
}

interface Party {
  id: string;
  name: string;
  role: string;
  email: string | null;
  phone: string | null;
}

interface Doc {
  id: string;
  title: string;
  category: string;
  status: string;
  fileName: string;
  fileSize: number | null;
  fileUrl: string;
  mimeType: string | null;
  createdAt: Date;
  uploadedByName: string | null;
}

interface Invoice {
  id: string;
  invoiceNumber: string;
  status: string;
  totalAmount: string | null;
  paidAmount: string | null;
  dueDate: Date | null;
  createdAt: Date;
}

interface TimeEntry {
  id: string;
  description: string | null;
  date: Date;
  hours: string | null;
  rate: string | null;
  amount: string | null;
  isBillable: boolean;
  isBilled: boolean;
  userName: string | null;
  userAvatar: string | null;
}

interface Expense {
  id: string;
  category: string;
  description: string | null;
  amount: string | null;
  date: Date;
  isBillable: boolean;
  isBilled: boolean;
  userName: string | null;
  userAvatar: string | null;
}

interface Deadline {
  id: string;
  title: string;
  description: string | null;
  priority: string;
  dueDate: Date;
  completedAt: Date | null;
  isStatutory: boolean;
}

interface Task {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  dueDate: Date | null;
  assignedToName: string | null;
}

interface UserOption {
  id: string;
  name: string | null;
}

interface CaseDetailTabsProps {
  caseData: CaseDetail;
  assignments: Assignment[];
  notes: Note[];
  timeline: TimelineEvent[];
  parties: Party[];
  documents: Doc[];
  invoices: Invoice[];
  timeEntries: TimeEntry[];
  expenses: Expense[];
  deadlines: Deadline[];
  tasks: Task[];
  users: UserOption[];
  sidebar?: React.ReactNode;
}

function TabCount({ count }: { count: number }) {
  if (count === 0) return null;
  return (
    <span className="ml-1.5 inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-muted px-1.5 text-[10px] font-semibold tabular-nums">
      {count}
    </span>
  );
}

function DL({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-0.5">
      <dt className="text-xs text-muted-foreground">{label}</dt>
      <dd className="text-sm font-medium">{children}</dd>
    </div>
  );
}

const timelineEventColors: Record<string, string> = {
  status_change: "bg-blue-500",
  note_added: "bg-emerald-500",
  assignment: "bg-purple-500",
  filing: "bg-amber-500",
  hearing: "bg-rose-500",
  document: "bg-cyan-500",
};

export function CaseDetailTabs({
  caseData,
  assignments,
  notes,
  timeline,
  parties,
  documents,
  invoices,
  timeEntries,
  expenses,
  deadlines,
  tasks,
  users,
  sidebar,
}: CaseDetailTabsProps) {
  return (
    <Tabs defaultValue="details">
      {/* Tab bar spans full width */}
      <TabsList className="flex-wrap h-auto gap-1">
        <TabsTrigger value="details">
          <Scale className="mr-1.5 h-3.5 w-3.5" />
          Details
        </TabsTrigger>
        <TabsTrigger value="financial">
          <CircleDollarSign className="mr-1.5 h-3.5 w-3.5" />
          Financial
          <TabCount count={invoices.length + timeEntries.length + expenses.length} />
        </TabsTrigger>
        <TabsTrigger value="tasks-deadlines">
          <ListTodo className="mr-1.5 h-3.5 w-3.5" />
          Tasks & Deadlines
          <TabCount count={tasks.length + deadlines.length} />
        </TabsTrigger>
        <TabsTrigger value="documents">
          <FileText className="mr-1.5 h-3.5 w-3.5" />
          Documents
          <TabCount count={documents.length} />
        </TabsTrigger>
        <TabsTrigger value="assignments">
          <Users className="mr-1.5 h-3.5 w-3.5" />
          Team
          <TabCount count={assignments.length} />
        </TabsTrigger>
        <TabsTrigger value="parties">
          Parties
          <TabCount count={parties.length} />
        </TabsTrigger>
        <TabsTrigger value="notes">
          <MessageSquare className="mr-1.5 h-3.5 w-3.5" />
          Notes
          <TabCount count={notes.length} />
        </TabsTrigger>
        <TabsTrigger value="timeline">
          <Clock className="mr-1.5 h-3.5 w-3.5" />
          Timeline
        </TabsTrigger>
      </TabsList>

      {/* Two-column layout: tab content + sidebar start at same level */}
      <div className="mt-4 grid gap-6 lg:grid-cols-[1fr_320px]">
        <div className="min-w-0">

      {/* ── Details ── */}
      <TabsContent value="details" className="mt-0">
        <Card>
          <CardContent className="p-6 space-y-6">
            {/* Case Info */}
            <div>
              <h3 className="text-sm font-semibold mb-3">Case Information</h3>
              <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <DL label="Case Type">{formatEnum(caseData.caseType)}</DL>
                {caseData.practiceArea && (
                  <DL label="Practice Area">{caseData.practiceArea}</DL>
                )}
                {caseData.dateFiled && (
                  <DL label="Date Filed">
                    {new Date(caseData.dateFiled).toLocaleDateString(APP_LOCALE)}
                  </DL>
                )}
                {caseData.statuteOfLimitations && (
                  <DL label="Statute of Limitations">
                    <span className={new Date(caseData.statuteOfLimitations) < new Date() ? "text-destructive" : ""}>
                      {new Date(caseData.statuteOfLimitations).toLocaleDateString(APP_LOCALE)}
                    </span>
                  </DL>
                )}
                {caseData.estimatedValue && (
                  <DL label="Estimated Value">{formatKES(Number(caseData.estimatedValue))}</DL>
                )}
              </dl>
              {caseData.description && (
                <div className="mt-4">
                  <dt className="text-xs text-muted-foreground mb-1">Description</dt>
                  <dd className="text-sm whitespace-pre-wrap leading-relaxed rounded-lg bg-muted/50 p-3">
                    {caseData.description}
                  </dd>
                </div>
              )}
            </div>

            <Separator />

            {/* Court & Opposition */}
            <div>
              <h3 className="text-sm font-semibold mb-3">Court &amp; Opposition</h3>
              <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <DL label="Court">{caseData.courtName ?? "—"}</DL>
                <DL label="Court Case #">{caseData.courtCaseNumber ?? "—"}</DL>
                <DL label="Judge">{caseData.judge ?? "—"}</DL>
                <DL label="Opposing Party">{caseData.opposingParty ?? "—"}</DL>
                <DL label="Opposing Counsel">{caseData.opposingCounsel ?? "—"}</DL>
              </dl>
            </div>

            <Separator />

            {/* Billing */}
            <div>
              <h3 className="text-sm font-semibold mb-3">Billing</h3>
              <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <DL label="Billing Type">{formatEnum(caseData.billingType)}</DL>
                {caseData.hourlyRate && (
                  <DL label="Hourly Rate">{formatKES(Number(caseData.hourlyRate))}/hr</DL>
                )}
                {caseData.flatFeeAmount && (
                  <DL label="Flat Fee">{formatKES(Number(caseData.flatFeeAmount))}</DL>
                )}
                {caseData.contingencyPercentage && (
                  <DL label="Contingency">{caseData.contingencyPercentage}%</DL>
                )}
              </dl>
            </div>
          </CardContent>
        </Card>
      </TabsContent>

      {/* ── Financial ── */}
      <TabsContent value="financial" className="mt-0 space-y-6">
        {/* Invoices */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <Receipt className="h-4 w-4 text-muted-foreground" />
                Invoices
              </CardTitle>
              <Link
                href={`/billing?caseId=${caseData.id}`}
                className="text-xs text-primary hover:underline flex items-center gap-1"
              >
                View all <ArrowUpRight className="h-3 w-3" />
              </Link>
            </div>
          </CardHeader>
          <CardContent className="pt-0">
            {invoices.length === 0 ? (
              <p className="py-6 text-center text-sm text-muted-foreground">
                No invoices for this case yet.
              </p>
            ) : (
              <div className="space-y-2">
                {invoices.map((inv) => {
                  const total = Number(inv.totalAmount || 0);
                  const paid = Number(inv.paidAmount || 0);
                  const pctPaid = total > 0 ? Math.min(100, (paid / total) * 100) : 0;
                  return (
                    <Link
                      key={inv.id}
                      href={`/billing/${inv.id}`}
                      className="flex items-center gap-3 rounded-lg border p-3 transition-colors hover:bg-muted/50"
                    >
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-xs font-medium">{inv.invoiceNumber}</span>
                          <InvoiceStatusBadge status={inv.status} />
                        </div>
                        <div className="mt-1.5 flex items-center gap-3">
                          <TooltipProvider>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <div className="flex-1 max-w-[200px]">
                                  <Progress value={pctPaid} className="h-1.5" />
                                </div>
                              </TooltipTrigger>
                              <TooltipContent>
                                {formatKES(paid)} of {formatKES(total)} paid ({Math.round(pctPaid)}%)
                              </TooltipContent>
                            </Tooltip>
                          </TooltipProvider>
                          <span className="text-[10px] text-muted-foreground shrink-0">
                            {formatKES(paid)} / {formatKES(total)}
                          </span>
                        </div>
                      </div>
                      <div className="text-right shrink-0">
                        <p className="text-sm font-semibold">{formatKES(total)}</p>
                        {inv.dueDate && (
                          <p className="text-[10px] text-muted-foreground">
                            Due {formatRelativeDate(new Date(inv.dueDate))}
                          </p>
                        )}
                      </div>
                    </Link>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Time Entries */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <Timer className="h-4 w-4 text-muted-foreground" />
                Time Entries
              </CardTitle>
              <Link
                href={`/time-expenses?caseId=${caseData.id}`}
                className="text-xs text-primary hover:underline flex items-center gap-1"
              >
                View all <ArrowUpRight className="h-3 w-3" />
              </Link>
            </div>
          </CardHeader>
          <CardContent className="pt-0">
            {timeEntries.length === 0 ? (
              <p className="py-6 text-center text-sm text-muted-foreground">
                No time entries recorded.
              </p>
            ) : (
              <div className="space-y-1">
                {timeEntries.slice(0, 10).map((entry) => (
                  <div
                    key={entry.id}
                    className="flex items-center gap-3 rounded-lg p-2.5 hover:bg-muted/50"
                  >
                    <PersonAvatar name={entry.userName} imageUrl={entry.userAvatar} size="sm" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm truncate">{entry.description || "Time entry"}</p>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className="text-[10px] text-muted-foreground">
                          {new Date(entry.date).toLocaleDateString(APP_LOCALE)}
                        </span>
                        <BillableBadge billable={entry.isBillable} />
                      </div>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-sm font-semibold tabular-nums">{Number(entry.hours || 0).toFixed(1)}h</p>
                      {entry.amount && (
                        <p className="text-[10px] text-muted-foreground">{formatKES(Number(entry.amount))}</p>
                      )}
                    </div>
                  </div>
                ))}
                {timeEntries.length > 10 && (
                  <p className="pt-2 text-center text-xs text-muted-foreground">
                    + {timeEntries.length - 10} more entries
                  </p>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Expenses */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <CircleDollarSign className="h-4 w-4 text-muted-foreground" />
                Expenses
              </CardTitle>
              <Link
                href={`/time-expenses?tab=expenses&caseId=${caseData.id}`}
                className="text-xs text-primary hover:underline flex items-center gap-1"
              >
                View all <ArrowUpRight className="h-3 w-3" />
              </Link>
            </div>
          </CardHeader>
          <CardContent className="pt-0">
            {expenses.length === 0 ? (
              <p className="py-6 text-center text-sm text-muted-foreground">
                No expenses recorded.
              </p>
            ) : (
              <div className="space-y-1">
                {expenses.slice(0, 10).map((exp) => (
                  <div
                    key={exp.id}
                    className="flex items-center gap-3 rounded-lg p-2.5 hover:bg-muted/50"
                  >
                    <PersonAvatar name={exp.userName} imageUrl={exp.userAvatar} size="sm" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm truncate">{exp.description || formatEnum(exp.category)}</p>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className="text-[10px] text-muted-foreground">
                          {new Date(exp.date).toLocaleDateString(APP_LOCALE)}
                        </span>
                        <Badge variant="outline" className="text-[10px]">
                          {formatEnum(exp.category)}
                        </Badge>
                      </div>
                    </div>
                    <p className="text-sm font-semibold shrink-0">{formatKES(Number(exp.amount || 0))}</p>
                  </div>
                ))}
                {expenses.length > 10 && (
                  <p className="pt-2 text-center text-xs text-muted-foreground">
                    + {expenses.length - 10} more expenses
                  </p>
                )}
              </div>
            )}
          </CardContent>
        </Card>
      </TabsContent>

      {/* ── Tasks & Deadlines ── */}
      <TabsContent value="tasks-deadlines" className="mt-0 space-y-6">
        {/* Deadlines */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <CalendarClock className="h-4 w-4 text-muted-foreground" />
                Deadlines
              </CardTitle>
              <div className="flex items-center gap-2">
                <AddDeadlineDialog caseId={caseData.id} users={users} />
                <Link
                  href="/deadlines"
                  className="text-xs text-primary hover:underline flex items-center gap-1"
                >
                  View all <ArrowUpRight className="h-3 w-3" />
                </Link>
              </div>
            </div>
          </CardHeader>
          <CardContent className="pt-0">
            {deadlines.length === 0 ? (
              <p className="py-6 text-center text-sm text-muted-foreground">
                No deadlines set for this case.
              </p>
            ) : (
              <div className="space-y-2">
                {deadlines.map((d) => {
                  const isOverdue = !d.completedAt && new Date(d.dueDate) < new Date();
                  const isCompleted = !!d.completedAt;
                  return (
                    <div
                      key={d.id}
                      className={`flex items-start gap-3 rounded-lg border p-3 ${
                        isOverdue ? "border-destructive/30 bg-destructive/5" : isCompleted ? "opacity-60" : ""
                      }`}
                    >
                      <div className="mt-0.5 shrink-0">
                        {isCompleted ? (
                          <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                        ) : isOverdue ? (
                          <AlertCircle className="h-4 w-4 text-destructive" />
                        ) : (
                          <CalendarClock className="h-4 w-4 text-muted-foreground" />
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <p className={`text-sm font-medium ${isCompleted ? "line-through" : ""}`}>
                            {d.title}
                          </p>
                          <PriorityBadge priority={d.priority} />
                          {d.isStatutory && (
                            <Badge variant="secondary" className="text-[10px]">Statutory</Badge>
                          )}
                        </div>
                        {d.description && (
                          <p className="text-xs text-muted-foreground mt-0.5 line-clamp-1">{d.description}</p>
                        )}
                        <p className={`text-[10px] mt-1 ${isOverdue ? "text-destructive font-medium" : "text-muted-foreground"}`}>
                          {isCompleted
                            ? `Completed ${formatRelativeDate(new Date(d.completedAt!))}`
                            : `Due ${formatRelativeDate(new Date(d.dueDate))}`}
                        </p>
                      </div>
                      <div className="flex items-center gap-1 shrink-0">
                        {!isCompleted && <CompleteDeadlineButton deadlineId={d.id} />}
                        <AddDeadlineDialog
                          caseId={caseData.id}
                          deadline={d}
                          users={users}
                          trigger={
                            <button className="inline-flex h-7 w-7 items-center justify-center rounded-md hover:bg-muted text-muted-foreground">
                              <Pencil className="h-3.5 w-3.5" />
                            </button>
                          }
                        />
                        <DeleteDeadlineButton deadlineId={d.id} />
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Tasks */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <ListTodo className="h-4 w-4 text-muted-foreground" />
                Tasks
              </CardTitle>
              <div className="flex items-center gap-2">
                <AddTaskDialog caseId={caseData.id} users={users} />
                <Link
                  href="/tasks"
                  className="text-xs text-primary hover:underline flex items-center gap-1"
                >
                  View all <ArrowUpRight className="h-3 w-3" />
                </Link>
              </div>
            </div>
          </CardHeader>
          <CardContent className="pt-0">
            {tasks.length === 0 ? (
              <p className="py-6 text-center text-sm text-muted-foreground">
                No tasks created for this case.
              </p>
            ) : (
              <div className="space-y-2">
                {tasks.map((t) => (
                  <div
                    key={t.id}
                    className={`flex items-start gap-3 rounded-lg border p-3 ${
                      t.status === "completed" ? "opacity-60" : ""
                    }`}
                  >
                    <div className="mt-0.5 shrink-0">
                      {t.status === "completed" ? (
                        <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                      ) : (
                        <ListTodo className="h-4 w-4 text-muted-foreground" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <p className={`text-sm font-medium ${t.status === "completed" ? "line-through" : ""}`}>
                          {t.title}
                        </p>
                        <TaskStatusBadge status={t.status} />
                        <PriorityBadge priority={t.priority} />
                      </div>
                      {t.description && (
                        <p className="text-xs text-muted-foreground mt-0.5 line-clamp-1">{t.description}</p>
                      )}
                      <div className="flex items-center gap-2 mt-1">
                        {t.assignedToName && (
                          <span className="text-[10px] text-muted-foreground">
                            Assigned to {t.assignedToName}
                          </span>
                        )}
                        {t.dueDate && (
                          <span className="text-[10px] text-muted-foreground">
                            · Due {formatRelativeDate(new Date(t.dueDate))}
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      <TaskStatusButton taskId={t.id} status={t.status} />
                      <AddTaskDialog
                        caseId={caseData.id}
                        task={t}
                        users={users}
                        trigger={
                          <button className="inline-flex h-7 w-7 items-center justify-center rounded-md hover:bg-muted text-muted-foreground">
                            <Pencil className="h-3.5 w-3.5" />
                          </button>
                        }
                      />
                      <DeleteTaskButton taskId={t.id} />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </TabsContent>

      {/* ── Documents ── */}
      <TabsContent value="documents" className="mt-0">
        <CaseDocumentsTab caseId={caseData.id} documents={documents} />
      </TabsContent>

      {/* ── Assignments (Team) ── */}
      <TabsContent value="assignments" className="mt-0 space-y-4">
        <div className="flex justify-end">
          <AssignMemberDialog caseId={caseData.id} users={users} />
        </div>
        {assignments.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No attorneys assigned.
          </p>
        ) : (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {assignments.map((a) => (
              <Card key={a.id}>
                <CardContent className="flex items-center gap-3 p-4">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">
                    {(a.userName ?? "?").charAt(0).toUpperCase()}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium truncate">{a.userName}</p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <Badge variant="outline" className="text-[10px]">
                        {formatEnum(a.role)}
                      </Badge>
                      <span className="text-[10px] text-muted-foreground">
                        {new Date(a.assignedAt).toLocaleDateString(APP_LOCALE)}
                      </span>
                    </div>
                  </div>
                  <UnassignButton assignmentId={a.id} caseId={caseData.id} />
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </TabsContent>

      {/* ── Parties ── */}
      <TabsContent value="parties" className="mt-0 space-y-4">
        <div className="flex justify-end">
          <AddPartyDialog caseId={caseData.id} />
        </div>
        {parties.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No parties added.
          </p>
        ) : (
          <div className="grid gap-3 sm:grid-cols-2">
            {parties.map((p) => (
              <Card key={p.id}>
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium">{p.name}</p>
                      <Badge variant="outline" className="text-[10px]">
                        {formatEnum(p.role)}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-1">
                      <AddPartyDialog
                        caseId={caseData.id}
                        party={p}
                        trigger={
                          <button className="inline-flex h-7 w-7 items-center justify-center rounded-md hover:bg-muted text-muted-foreground">
                            <Pencil className="h-3.5 w-3.5" />
                          </button>
                        }
                      />
                      <DeletePartyButton partyId={p.id} caseId={caseData.id} />
                    </div>
                  </div>
                  <div className="space-y-0.5 text-xs text-muted-foreground">
                    {p.email && <p>{p.email}</p>}
                    {p.phone && <p>{p.phone}</p>}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </TabsContent>

      {/* ── Notes ── */}
      <TabsContent value="notes" className="mt-0 space-y-4">
        <div className="flex justify-end">
          <AddNoteDialog caseId={caseData.id} />
        </div>
        {notes.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No notes added.
          </p>
        ) : (
          <div className="space-y-3">
            {notes.map((n) => (
              <Card key={n.id}>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary">
                      {(n.authorName ?? "?").charAt(0).toUpperCase()}
                    </div>
                    <span className="text-sm font-medium">{n.authorName}</span>
                    <div className="ml-auto flex items-center gap-2">
                      {n.isPrivate && (
                        <Badge variant="secondary" className="text-[10px]">
                          Private
                        </Badge>
                      )}
                      <span className="text-[10px] text-muted-foreground">
                        {new Date(n.createdAt).toLocaleString(APP_LOCALE)}
                      </span>
                      <AddNoteDialog
                        caseId={caseData.id}
                        note={n}
                        trigger={
                          <button className="inline-flex h-7 w-7 items-center justify-center rounded-md hover:bg-muted text-muted-foreground">
                            <Pencil className="h-3.5 w-3.5" />
                          </button>
                        }
                      />
                      <DeleteNoteButton noteId={n.id} caseId={caseData.id} />
                    </div>
                  </div>
                  <p className="text-sm whitespace-pre-wrap leading-relaxed pl-9">
                    {n.content}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </TabsContent>

      {/* ── Timeline ── */}
      <TabsContent value="timeline" className="mt-0">
        {timeline.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No activity recorded.
          </p>
        ) : (
          <div className="relative ml-3 border-l border-border pl-6 space-y-6">
            {timeline.map((e) => {
              const dotColor =
                timelineEventColors[e.eventType] ?? "bg-muted-foreground";
              return (
                <div key={e.id} className="relative">
                  {/* Dot */}
                  <div
                    className={`absolute -left-[calc(1.5rem+5px)] top-1.5 h-2.5 w-2.5 rounded-full ring-2 ring-background ${dotColor}`}
                  />
                  <div>
                    <p className="text-sm font-medium">{e.title}</p>
                    {e.description && (
                      <p className="text-sm text-muted-foreground mt-0.5">
                        {e.description}
                      </p>
                    )}
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-[10px] text-muted-foreground">
                        {new Date(e.createdAt).toLocaleString(APP_LOCALE)}
                      </span>
                      {e.userName && (
                        <span className="text-[10px] text-muted-foreground">
                          by {e.userName}
                        </span>
                      )}
                      <Badge variant="outline" className="text-[10px]">
                        {formatEnum(e.eventType)}
                      </Badge>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </TabsContent>

        </div>{/* end left column */}

        {/* Sidebar — aligned with tab content */}
        {sidebar && (
          <div className="hidden lg:block">
            {sidebar}
          </div>
        )}
      </div>{/* end grid */}
    </Tabs>
  );
}
