"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { formatKES } from "@/lib/utils/format";
import { formatEnum } from "@/lib/utils/format-enum";
import { Clock, Users, MessageSquare } from "lucide-react";
import { APP_LOCALE } from "@/lib/constants/locale";

interface CaseDetail {
  id: string;
  caseNumber: string;
  title: string;
  status: string;
  priority: string;
  caseType: string;
  practiceArea: string | null;
  billingType: string;
  hourlyRate: string | null;
  flatFeeAmount: string | null;
  contingencyPercentage: string | null;
  courtName: string | null;
  courtCaseNumber: string | null;
  judge: string | null;
  opposingCounsel: string | null;
  opposingParty: string | null;
  statuteOfLimitations: Date | null;
  dateFiled: Date | null;
  estimatedValue: string | null;
  description: string | null;
  notes: string | null;
  clientId: string;
  clientName: string;
  createdAt: Date;
}

interface Assignment {
  id: string;
  role: string;
  assignedAt: Date;
  userName: string | null;
  userId: string;
}

interface Note {
  id: string;
  content: string;
  isPrivate: boolean;
  createdAt: Date;
  authorName: string | null;
}

interface TimelineEvent {
  id: string;
  eventType: string;
  title: string;
  description: string | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  userName: string | null;
}

interface Party {
  id: string;
  name: string;
  role: string;
  email: string | null;
  phone: string | null;
}

interface CaseDetailTabsProps {
  caseData: CaseDetail;
  assignments: Assignment[];
  notes: Note[];
  timeline: TimelineEvent[];
  parties: Party[];
}

export function CaseDetailTabs({ caseData, assignments, notes, timeline, parties }: CaseDetailTabsProps) {
  return (
    <Tabs defaultValue="details" className="space-y-4">
      <TabsList>
        <TabsTrigger value="details">Details</TabsTrigger>
        <TabsTrigger value="assignments">Assignments</TabsTrigger>
        <TabsTrigger value="parties">Parties</TabsTrigger>
        <TabsTrigger value="notes">Notes</TabsTrigger>
        <TabsTrigger value="timeline">Timeline</TabsTrigger>
      </TabsList>

      <TabsContent value="details">
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Case Information</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="grid gap-3">
                <div>
                  <dt className="text-sm text-muted-foreground">Case Type</dt>
                  <dd className="font-medium capitalize">{formatEnum(caseData.caseType)}</dd>
                </div>
                {caseData.practiceArea && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Practice Area</dt>
                    <dd className="font-medium">{caseData.practiceArea}</dd>
                  </div>
                )}
                {caseData.description && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Description</dt>
                    <dd className="font-medium whitespace-pre-wrap">{caseData.description}</dd>
                  </div>
                )}
                {caseData.dateFiled && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Date Filed</dt>
                    <dd className="font-medium">
                      {new Date(caseData.dateFiled).toLocaleDateString(APP_LOCALE)}
                    </dd>
                  </div>
                )}
                {caseData.statuteOfLimitations && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Statute of Limitations</dt>
                    <dd className="font-medium">
                      {new Date(caseData.statuteOfLimitations).toLocaleDateString(APP_LOCALE)}
                    </dd>
                  </div>
                )}
                {caseData.estimatedValue && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Estimated Value</dt>
                    <dd className="font-medium">{formatKES(Number(caseData.estimatedValue))}</dd>
                  </div>
                )}
              </dl>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Court & Opposition</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="grid gap-3">
                <div>
                  <dt className="text-sm text-muted-foreground">Court</dt>
                  <dd className="font-medium">{caseData.courtName ?? "—"}</dd>
                </div>
                <div>
                  <dt className="text-sm text-muted-foreground">Court Case #</dt>
                  <dd className="font-medium">{caseData.courtCaseNumber ?? "—"}</dd>
                </div>
                <div>
                  <dt className="text-sm text-muted-foreground">Judge</dt>
                  <dd className="font-medium">{caseData.judge ?? "—"}</dd>
                </div>
                <div>
                  <dt className="text-sm text-muted-foreground">Opposing Party</dt>
                  <dd className="font-medium">{caseData.opposingParty ?? "—"}</dd>
                </div>
                <div>
                  <dt className="text-sm text-muted-foreground">Opposing Counsel</dt>
                  <dd className="font-medium">{caseData.opposingCounsel ?? "—"}</dd>
                </div>
              </dl>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Billing</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="grid gap-3">
                <div>
                  <dt className="text-sm text-muted-foreground">Billing Type</dt>
                  <dd className="font-medium capitalize">{formatEnum(caseData.billingType)}</dd>
                </div>
                {caseData.hourlyRate && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Hourly Rate</dt>
                    <dd className="font-medium">{formatKES(Number(caseData.hourlyRate))}/hr</dd>
                  </div>
                )}
                {caseData.flatFeeAmount && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Flat Fee</dt>
                    <dd className="font-medium">{formatKES(Number(caseData.flatFeeAmount))}</dd>
                  </div>
                )}
                {caseData.contingencyPercentage && (
                  <div>
                    <dt className="text-sm text-muted-foreground">Contingency</dt>
                    <dd className="font-medium">{caseData.contingencyPercentage}%</dd>
                  </div>
                )}
              </dl>
            </CardContent>
          </Card>
        </div>
      </TabsContent>

      <TabsContent value="assignments">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Users className="h-5 w-5" />
              Case Assignments
            </CardTitle>
          </CardHeader>
          <CardContent>
            {assignments.length === 0 ? (
              <p className="text-sm text-muted-foreground">No attorneys assigned.</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Attorney</TableHead>
                    <TableHead>Role</TableHead>
                    <TableHead>Assigned</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {assignments.map((a) => (
                    <TableRow key={a.id}>
                      <TableCell className="font-medium">{a.userName}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="capitalize">
                          {formatEnum(a.role)}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        {new Date(a.assignedAt).toLocaleDateString(APP_LOCALE)}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </TabsContent>

      <TabsContent value="parties">
        <Card>
          <CardHeader>
            <CardTitle>Case Parties</CardTitle>
          </CardHeader>
          <CardContent>
            {parties.length === 0 ? (
              <p className="text-sm text-muted-foreground">No parties added.</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Role</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Phone</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {parties.map((p) => (
                    <TableRow key={p.id}>
                      <TableCell className="font-medium">{p.name}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="capitalize">
                          {formatEnum(p.role)}
                        </Badge>
                      </TableCell>
                      <TableCell>{p.email ?? "—"}</TableCell>
                      <TableCell>{p.phone ?? "—"}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </TabsContent>

      <TabsContent value="notes">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <MessageSquare className="h-5 w-5" />
              Case Notes
            </CardTitle>
          </CardHeader>
          <CardContent>
            {notes.length === 0 ? (
              <p className="text-sm text-muted-foreground">No notes added.</p>
            ) : (
              <div className="space-y-4">
                {notes.map((n) => (
                  <div key={n.id} className="rounded-md border p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium">{n.authorName}</span>
                      <div className="flex items-center gap-2">
                        {n.isPrivate && <Badge variant="secondary">Private</Badge>}
                        <span className="text-xs text-muted-foreground">
                          {new Date(n.createdAt).toLocaleString(APP_LOCALE)}
                        </span>
                      </div>
                    </div>
                    <p className="text-sm whitespace-pre-wrap">{n.content}</p>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </TabsContent>

      <TabsContent value="timeline">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="h-5 w-5" />
              Activity Timeline
            </CardTitle>
          </CardHeader>
          <CardContent>
            {timeline.length === 0 ? (
              <p className="text-sm text-muted-foreground">No activity recorded.</p>
            ) : (
              <div className="space-y-4">
                {timeline.map((e) => (
                  <div key={e.id} className="flex gap-4 border-l-2 pl-4 pb-4">
                    <div className="flex-1">
                      <p className="font-medium text-sm">{e.title}</p>
                      {e.description && (
                        <p className="text-sm text-muted-foreground">{e.description}</p>
                      )}
                      <div className="flex items-center gap-2 mt-1">
                        <span className="text-xs text-muted-foreground">
                          {new Date(e.createdAt).toLocaleString(APP_LOCALE)}
                        </span>
                        {e.userName && (
                          <span className="text-xs text-muted-foreground">by {e.userName}</span>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </TabsContent>
    </Tabs>
  );
}
