import { pgTable, uuid, text, boolean, timestamp, numeric, integer, index, uniqueIndex } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { caseStatus, casePriority, billingType, casePartyRole, assignmentRole } from "./enums";
import { users } from "./auth";
import { clients } from "./clients";
import { practiceAreas } from "./settings";

export const cases = pgTable(
  "cases",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    caseNumber: text("case_number").notNull().unique(),
    title: text("title").notNull(),
    clientId: uuid("client_id")
      .notNull()
      .references(() => clients.id, { onDelete: "restrict" }),
    status: caseStatus("status").notNull().default("open"),
    priority: casePriority("priority").notNull().default("medium"),
    caseType: text("case_type").notNull(),
    practiceArea: text("practice_area"),
    billingType: billingType("billing_type").notNull().default("hourly"),
    hourlyRate: numeric("hourly_rate", { precision: 10, scale: 2 }),
    flatFeeAmount: numeric("flat_fee_amount", { precision: 12, scale: 2 }),
    contingencyPercentage: numeric("contingency_percentage", { precision: 5, scale: 2 }),
    courtName: text("court_name"),
    courtCaseNumber: text("court_case_number"),
    judge: text("judge"),
    opposingCounsel: text("opposing_counsel"),
    opposingParty: text("opposing_party"),
    statuteOfLimitations: timestamp("statute_of_limitations", { withTimezone: true }),
    dateFiled: timestamp("date_filed", { withTimezone: true }),
    estimatedValue: numeric("estimated_value", { precision: 14, scale: 2 }),
    description: text("description"),
    notes: text("notes"),
    pipelineStageId: uuid("pipeline_stage_id").references(() => pipelineStages.id, { onDelete: "set null" }),
    stageEnteredAt: timestamp("stage_entered_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("cases_case_number_idx").on(table.caseNumber),
    index("cases_status_idx").on(table.status),
    index("cases_client_id_idx").on(table.clientId),
    index("cases_priority_idx").on(table.priority),
  ]
);

export const caseAssignments = pgTable(
  "case_assignments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    caseId: uuid("case_id")
      .notNull()
      .references(() => cases.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    role: assignmentRole("role").notNull().default("assigned"),
    assignedAt: timestamp("assigned_at", { withTimezone: true }).defaultNow().notNull(),
    unassignedAt: timestamp("unassigned_at", { withTimezone: true }),
  },
  (table) => [
    index("case_assignments_user_id_idx").on(table.userId),
    index("case_assignments_case_id_idx").on(table.caseId),
    uniqueIndex("case_assignments_case_user_idx").on(table.caseId, table.userId),
  ]
);

export const caseNotes = pgTable("case_notes", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  authorId: uuid("author_id")
    .notNull()
    .references(() => users.id, { onDelete: "restrict" }),
  content: text("content").notNull(),
  isPrivate: boolean("is_private").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const caseTimeline = pgTable("case_timeline", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
  eventType: text("event_type").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const caseParties = pgTable("case_parties", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  role: casePartyRole("role").notNull(),
  email: text("email"),
  phone: text("phone"),
  address: text("address"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const pipelineStages = pgTable("pipeline_stages", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  description: text("description"),
  order: integer("order").notNull(),
  color: text("color"),
  isDefault: boolean("is_default").notNull().default(false),
  practiceAreaId: uuid("practice_area_id").references(() => practiceAreas.id, { onDelete: "cascade" }),
  maxDurationDays: integer("max_duration_days"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const caseStageHistory = pgTable(
  "case_stage_history",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    caseId: uuid("case_id")
      .notNull()
      .references(() => cases.id, { onDelete: "cascade" }),
    stageId: uuid("stage_id")
      .notNull()
      .references(() => pipelineStages.id, { onDelete: "cascade" }),
    enteredAt: timestamp("entered_at", { withTimezone: true }).notNull(),
    exitedAt: timestamp("exited_at", { withTimezone: true }),
    movedBy: uuid("moved_by").references(() => users.id, { onDelete: "set null" }),
  },
  (table) => [
    index("case_stage_history_case_id_idx").on(table.caseId),
    index("case_stage_history_stage_id_idx").on(table.stageId),
    index("case_stage_history_entered_at_idx").on(table.enteredAt),
  ]
);

export const stageAutomations = pgTable("stage_automations", {
  id: uuid("id").primaryKey().defaultRandom(),
  stageId: uuid("stage_id")
    .notNull()
    .references(() => pipelineStages.id, { onDelete: "cascade" }),
  triggerOn: text("trigger_on").notNull(), // "enter" | "exit"
  actionType: text("action_type").notNull(), // "send_notification" | "create_task" | "update_status"
  actionConfig: text("action_config"), // JSON string
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const casesRelations = relations(cases, ({ one, many }) => ({
  client: one(clients, { fields: [cases.clientId], references: [clients.id] }),
  pipelineStage: one(pipelineStages, {
    fields: [cases.pipelineStageId],
    references: [pipelineStages.id],
  }),
  assignments: many(caseAssignments),
  notes: many(caseNotes),
  timeline: many(caseTimeline),
  parties: many(caseParties),
  stageHistory: many(caseStageHistory),
}));

export const caseAssignmentsRelations = relations(caseAssignments, ({ one }) => ({
  case: one(cases, { fields: [caseAssignments.caseId], references: [cases.id] }),
  user: one(users, { fields: [caseAssignments.userId], references: [users.id] }),
}));

export const caseNotesRelations = relations(caseNotes, ({ one }) => ({
  case: one(cases, { fields: [caseNotes.caseId], references: [cases.id] }),
  author: one(users, { fields: [caseNotes.authorId], references: [users.id] }),
}));

export const caseTimelineRelations = relations(caseTimeline, ({ one }) => ({
  case: one(cases, { fields: [caseTimeline.caseId], references: [cases.id] }),
  user: one(users, { fields: [caseTimeline.userId], references: [users.id] }),
}));

export const casePartiesRelations = relations(caseParties, ({ one }) => ({
  case: one(cases, { fields: [caseParties.caseId], references: [cases.id] }),
}));

export const pipelineStagesRelations = relations(pipelineStages, ({ one, many }) => ({
  practiceArea: one(practiceAreas, {
    fields: [pipelineStages.practiceAreaId],
    references: [practiceAreas.id],
  }),
  automations: many(stageAutomations),
  history: many(caseStageHistory),
}));

export const caseStageHistoryRelations = relations(caseStageHistory, ({ one }) => ({
  case: one(cases, { fields: [caseStageHistory.caseId], references: [cases.id] }),
  stage: one(pipelineStages, { fields: [caseStageHistory.stageId], references: [pipelineStages.id] }),
  movedByUser: one(users, { fields: [caseStageHistory.movedBy], references: [users.id] }),
}));

export const stageAutomationsRelations = relations(stageAutomations, ({ one }) => ({
  stage: one(pipelineStages, { fields: [stageAutomations.stageId], references: [pipelineStages.id] }),
}));
