import { pgTable, uuid, text, boolean, timestamp, numeric, integer, index } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { caseStatus, casePriority, billingType, casePartyRole, assignmentRole } from "./enums";
import { users } from "./auth";
import { clients } from "./clients";

export const cases = pgTable(
  "cases",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    caseNumber: text("case_number").notNull().unique(),
    title: text("title").notNull(),
    clientId: uuid("client_id")
      .notNull()
      .references(() => clients.id, { onDelete: "restrict" }),
    status: caseStatus("status").notNull().default("open"),
    priority: casePriority("priority").notNull().default("medium"),
    caseType: text("case_type").notNull(),
    practiceArea: text("practice_area"),
    billingType: billingType("billing_type").notNull().default("hourly"),
    hourlyRate: numeric("hourly_rate", { precision: 10, scale: 2 }),
    flatFeeAmount: numeric("flat_fee_amount", { precision: 12, scale: 2 }),
    contingencyPercentage: numeric("contingency_percentage", { precision: 5, scale: 2 }),
    courtName: text("court_name"),
    courtCaseNumber: text("court_case_number"),
    judge: text("judge"),
    opposingCounsel: text("opposing_counsel"),
    opposingParty: text("opposing_party"),
    statuteOfLimitations: timestamp("statute_of_limitations", { withTimezone: true }),
    dateFiled: timestamp("date_filed", { withTimezone: true }),
    estimatedValue: numeric("estimated_value", { precision: 14, scale: 2 }),
    description: text("description"),
    notes: text("notes"),
    pipelineStageId: uuid("pipeline_stage_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("cases_case_number_idx").on(table.caseNumber),
    index("cases_status_idx").on(table.status),
    index("cases_client_id_idx").on(table.clientId),
    index("cases_priority_idx").on(table.priority),
  ]
);

export const caseAssignments = pgTable("case_assignments", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  role: assignmentRole("role").notNull().default("assigned"),
  assignedAt: timestamp("assigned_at", { withTimezone: true }).defaultNow().notNull(),
  unassignedAt: timestamp("unassigned_at", { withTimezone: true }),
});

export const caseNotes = pgTable("case_notes", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  authorId: uuid("author_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  content: text("content").notNull(),
  isPrivate: boolean("is_private").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const caseTimeline = pgTable("case_timeline", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
  eventType: text("event_type").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const caseParties = pgTable("case_parties", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  role: casePartyRole("role").notNull(),
  email: text("email"),
  phone: text("phone"),
  address: text("address"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const pipelineStages = pgTable("pipeline_stages", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  description: text("description"),
  order: integer("order").notNull(),
  color: text("color"),
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const casesRelations = relations(cases, ({ one, many }) => ({
  client: one(clients, { fields: [cases.clientId], references: [clients.id] }),
  pipelineStage: one(pipelineStages, {
    fields: [cases.pipelineStageId],
    references: [pipelineStages.id],
  }),
  assignments: many(caseAssignments),
  notes: many(caseNotes),
  timeline: many(caseTimeline),
  parties: many(caseParties),
}));

export const caseAssignmentsRelations = relations(caseAssignments, ({ one }) => ({
  case: one(cases, { fields: [caseAssignments.caseId], references: [cases.id] }),
  user: one(users, { fields: [caseAssignments.userId], references: [users.id] }),
}));

export const caseNotesRelations = relations(caseNotes, ({ one }) => ({
  case: one(cases, { fields: [caseNotes.caseId], references: [cases.id] }),
  author: one(users, { fields: [caseNotes.authorId], references: [users.id] }),
}));

export const caseTimelineRelations = relations(caseTimeline, ({ one }) => ({
  case: one(cases, { fields: [caseTimeline.caseId], references: [cases.id] }),
  user: one(users, { fields: [caseTimeline.userId], references: [users.id] }),
}));

export const casePartiesRelations = relations(caseParties, ({ one }) => ({
  case: one(cases, { fields: [caseParties.caseId], references: [cases.id] }),
}));
