"use server";

import { db } from "@/lib/db";
import { cases, caseAssignments, caseNotes, caseTimeline, caseParties, pipelineStages, caseStageHistory } from "@/lib/db/schema/cases";
import { clients, conflictChecks } from "@/lib/db/schema/clients";
import { auth } from "@/lib/auth/auth";
import { createAuditLog } from "@/lib/utils/audit";
import { createCaseSchema, updateCaseSchema, createCaseNoteSchema, addCasePartySchema, assignCaseSchema } from "@/lib/validators/case";
import { pipelineStageSchema } from "@/lib/validators/pipeline";
import { generateCaseNumber } from "@/lib/queries/cases";
import { executeStageAutomations } from "@/lib/actions/pipeline";
import { runConflictCheck } from "@/lib/actions/conflicts";
import { and, eq, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { safeAction } from "@/lib/utils/safe-action";
import { withUniqueRetry } from "@/lib/utils/with-retry";
import { dispatchWorkflowEvent } from "@/lib/workflows/engine";

async function isAssignedToCase(userId: string, caseId: string): Promise<boolean> {
  const [assignment] = await db
    .select({ id: caseAssignments.id })
    .from(caseAssignments)
    .where(and(
      eq(caseAssignments.caseId, caseId),
      eq(caseAssignments.userId, userId),
      sql`${caseAssignments.unassignedAt} IS NULL`
    ))
    .limit(1);
  return !!assignment;
}

export async function createCase(data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    const validated = createCaseSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const { hourlyRate, flatFeeAmount, contingencyPercentage, estimatedValue, statuteOfLimitations, dateFiled, conflictAcknowledged, ...rest } = validated.data;

    // --- Auto Conflict Check ---
    // Look up the client to get their name for conflict search
    const [client] = await db
      .select({ id: clients.id, firstName: clients.firstName, lastName: clients.lastName })
      .from(clients)
      .where(eq(clients.id, rest.clientId))
      .limit(1);
    if (!client) return { error: "Client not found" };

    const clientName = `${client.firstName} ${client.lastName}`;
    const conflictResult = await runConflictCheck(clientName);

    // Also check opposing party if provided
    if (rest.opposingParty) {
      const opposingResult = await runConflictCheck(rest.opposingParty);
      for (const m of opposingResult.matches) {
        // Avoid duplicate matches
        const isDuplicate = conflictResult.matches.some(
          (existing) => existing.type === m.type && existing.name === m.name && existing.detail === m.detail
        );
        if (!isDuplicate) {
          conflictResult.matches.push(m);
          conflictResult.hasConflict = true;
        }
      }
    }

    // Store conflict check result regardless
    const severity = conflictResult.hasConflict ? "potential" as const : "clear" as const;
    await db.insert(conflictChecks).values({
      clientId: client.id,
      searchQuery: rest.opposingParty
        ? `${clientName}; ${rest.opposingParty}`
        : clientName,
      result: severity,
      matchDetails: conflictResult.matches.length > 0
        ? JSON.stringify(conflictResult.matches)
        : null,
      checkedBy: session.user.id,
    });

    // If conflicts found and not acknowledged, return error with conflict details
    if (conflictResult.hasConflict && !conflictAcknowledged) {
      return {
        error: "Conflict detected",
        conflicts: conflictResult.matches,
      };
    }

    // Retry on unique constraint violation (concurrent number generation race)
    const result = await withUniqueRetry(async () => {
      const caseNumber = await generateCaseNumber();
      return await db
        .insert(cases)
        .values({
          ...rest,
          caseNumber,
          hourlyRate: hourlyRate ? String(hourlyRate) : undefined,
          flatFeeAmount: flatFeeAmount ? String(flatFeeAmount) : undefined,
          contingencyPercentage: contingencyPercentage ? String(contingencyPercentage) : undefined,
          estimatedValue: estimatedValue ? String(estimatedValue) : undefined,
          statuteOfLimitations: statuteOfLimitations ? new Date(statuteOfLimitations) : undefined,
          dateFiled: dateFiled ? new Date(dateFiled) : undefined,
        })
        .returning();
    });

    await db.insert(caseTimeline).values({
      caseId: result[0].id,
      userId: session.user.id,
      eventType: "case_created",
      title: "Case created",
      description: `Case ${result[0].caseNumber} was created`,
      isAutoGenerated: true,
    });

    await createAuditLog(
      session.user.id,
      "create",
      "case",
      result[0].id,
      { caseNumber: result[0].caseNumber, ...validated.data }
    );

    revalidatePath("/cases");
    return { data: result[0] };
  });
}

export async function updateCase(id: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    if (session.user.role === "attorney") {
      const assigned = await isAssignedToCase(session.user.id, id);
      if (!assigned) return { error: "You are not assigned to this case" };
    }

    const validated = updateCaseSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const {
      hourlyRate,
      flatFeeAmount,
      contingencyPercentage,
      estimatedValue,
      statuteOfLimitations,
      dateFiled,
      conflictAcknowledged,
      ...rest
    } = validated.data;
    void conflictAcknowledged;

    const result = await db
      .update(cases)
      .set({
        ...rest,
        hourlyRate: hourlyRate !== undefined ? String(hourlyRate) : undefined,
        flatFeeAmount: flatFeeAmount !== undefined ? String(flatFeeAmount) : undefined,
        contingencyPercentage: contingencyPercentage !== undefined ? String(contingencyPercentage) : undefined,
        estimatedValue: estimatedValue !== undefined ? String(estimatedValue) : undefined,
        statuteOfLimitations: statuteOfLimitations ? new Date(statuteOfLimitations) : undefined,
        dateFiled: dateFiled ? new Date(dateFiled) : undefined,
        updatedAt: new Date(),
      })
      .where(eq(cases.id, id))
      .returning();

    if (validated.data.status) {
      await db.insert(caseTimeline).values({
        caseId: id,
        userId: session.user.id,
        eventType: "status_change",
        title: `Status changed to ${validated.data.status}`,
        isAutoGenerated: true,
      });

      // Fire workflow event for status change (fire-and-forget)
      dispatchWorkflowEvent("case_status_change", {
        entityId: id,
        entityType: "case",
        userId: session.user.id,
        data: { status: validated.data.status },
      }).catch(console.error);
    }

    await createAuditLog(
      session.user.id,
      "update",
      "case",
      id,
      { updated: validated.data }
    );

    revalidatePath("/cases");
    revalidatePath(`/cases/${id}`);
    return { data: result[0] };
  });
}

export async function addCaseNote(caseId: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    if (session.user.role === "attorney") {
      const assigned = await isAssignedToCase(session.user.id, caseId);
      if (!assigned) return { error: "You are not assigned to this case" };
    }

    const validated = createCaseNoteSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db
      .insert(caseNotes)
      .values({
        caseId,
        authorId: session.user.id,
        content: validated.data.content,
        isPrivate: validated.data.isPrivate,
      })
      .returning();

    revalidatePath(`/cases/${caseId}`);
    return { data: result[0] };
  });
}

export async function addCaseParty(caseId: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    if (session.user.role === "attorney") {
      const assigned = await isAssignedToCase(session.user.id, caseId);
      if (!assigned) return { error: "You are not assigned to this case" };
    }

    const validated = addCasePartySchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db
      .insert(caseParties)
      .values({
        caseId,
        ...validated.data,
      })
      .returning();

    revalidatePath(`/cases/${caseId}`);
    return { data: result[0] };
  });
}

export async function assignCase(caseId: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    const validated = assignCaseSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db
      .insert(caseAssignments)
      .values({
        caseId,
        userId: validated.data.userId,
        role: validated.data.role,
      })
      .returning();

    await db.insert(caseTimeline).values({
      caseId,
      userId: session.user.id,
      eventType: "assignment",
      title: `Attorney assigned (${validated.data.role})`,
      isAutoGenerated: true,
    });

    revalidatePath(`/cases/${caseId}`);
    return { data: result[0] };
  });
}

export async function unassignCase(assignmentId: string, caseId: string) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    // Verify assignment exists and belongs to the given case
    const [assignment] = await db
      .select({ id: caseAssignments.id })
      .from(caseAssignments)
      .where(and(eq(caseAssignments.id, assignmentId), eq(caseAssignments.caseId, caseId)))
      .limit(1);
    if (!assignment) return { error: "Assignment not found" };

    await db
      .update(caseAssignments)
      .set({ unassignedAt: new Date() })
      .where(eq(caseAssignments.id, assignmentId));

    revalidatePath(`/cases/${caseId}`);
    return { success: true };
  });
}

export async function updateCasePipelineStage(caseId: string, stageId: string) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(caseId) || !uuidRegex.test(stageId)) {
      return { error: "Invalid ID" };
    }

    // Fetch current case to get old stage
    const [currentCase] = await db
      .select({ pipelineStageId: cases.pipelineStageId })
      .from(cases)
      .where(eq(cases.id, caseId))
      .limit(1);
    if (!currentCase) return { error: "Case not found" };

    const now = new Date();
    const fromStageId = currentCase.pipelineStageId;

    // Close old history record if transitioning from a stage
    if (fromStageId) {
      await db
        .update(caseStageHistory)
        .set({ exitedAt: now })
        .where(
          and(
            eq(caseStageHistory.caseId, caseId),
            eq(caseStageHistory.stageId, fromStageId),
            sql`${caseStageHistory.exitedAt} IS NULL`
          )
        );
    }

    // Insert new history record
    await db.insert(caseStageHistory).values({
      caseId,
      stageId,
      enteredAt: now,
      movedBy: session.user.id,
    });

    // Update case
    await db
      .update(cases)
      .set({ pipelineStageId: stageId, stageEnteredAt: now, updatedAt: now })
      .where(eq(cases.id, caseId));

    // Timeline entry
    await db.insert(caseTimeline).values({
      caseId,
      userId: session.user.id,
      eventType: "pipeline_stage_change",
      title: "Pipeline stage changed",
      isAutoGenerated: true,
    });

    // Execute automations (fire-and-forget, errors logged not thrown)
    executeStageAutomations(caseId, stageId, fromStageId, session.user.id).catch(() => {});

    revalidatePath("/cases");
    revalidatePath("/cases/pipeline");
    return { success: true };
  });
}

// --- Pipeline Stages ---

export async function createPipelineStage(data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || session.user.role !== "admin") {
      return { error: "Unauthorized" };
    }

    const validated = pipelineStageSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db.insert(pipelineStages).values(validated.data).returning();

    revalidatePath("/cases/pipeline");
    revalidatePath("/settings");
    return { data: result[0] };
  });
}

export async function updatePipelineStage(id: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || session.user.role !== "admin") {
      return { error: "Unauthorized" };
    }

    const validated = pipelineStageSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    await db.update(pipelineStages).set(validated.data).where(eq(pipelineStages.id, id));

    revalidatePath("/cases/pipeline");
    revalidatePath("/settings");
    return { success: true };
  });
}

export async function deletePipelineStage(id: string) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || session.user.role !== "admin") {
      return { error: "Unauthorized" };
    }

    await db.delete(pipelineStages).where(eq(pipelineStages.id, id));

    revalidatePath("/cases/pipeline");
    revalidatePath("/settings");
    return { success: true };
  });
}
