"use server";

import { db } from "@/lib/db";
import { cases, caseAssignments, caseNotes, caseTimeline, caseParties } from "@/lib/db/schema/cases";
import { auth } from "@/lib/auth/auth";
import { createAuditLog } from "@/lib/utils/audit";
import { createCaseSchema, updateCaseSchema, createCaseNoteSchema, addCasePartySchema, assignCaseSchema } from "@/lib/validators/case";
import { generateCaseNumber } from "@/lib/queries/cases";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";

export async function createCase(data: unknown) {
  const session = await auth();
  if (!session?.user || !["admin", "attorney"].includes(session.user.role as string)) {
    return { error: "Unauthorized" };
  }

  const validated = createCaseSchema.safeParse(data);
  if (!validated.success) {
    return { error: validated.error.issues[0].message };
  }

  const caseNumber = await generateCaseNumber();
  const { hourlyRate, flatFeeAmount, contingencyPercentage, estimatedValue, statuteOfLimitations, dateFiled, ...rest } = validated.data;

  const result = await db
    .insert(cases)
    .values({
      ...rest,
      caseNumber,
      hourlyRate: hourlyRate ? String(hourlyRate) : undefined,
      flatFeeAmount: flatFeeAmount ? String(flatFeeAmount) : undefined,
      contingencyPercentage: contingencyPercentage ? String(contingencyPercentage) : undefined,
      estimatedValue: estimatedValue ? String(estimatedValue) : undefined,
      statuteOfLimitations: statuteOfLimitations ? new Date(statuteOfLimitations) : undefined,
      dateFiled: dateFiled ? new Date(dateFiled) : undefined,
    })
    .returning();

  await db.insert(caseTimeline).values({
    caseId: result[0].id,
    userId: session.user.id as string,
    eventType: "case_created",
    title: "Case created",
    description: `Case ${caseNumber} was created`,
    isAutoGenerated: true,
  });

  await createAuditLog(
    session.user.id as string,
    "create",
    "case",
    result[0].id,
    { caseNumber, ...validated.data }
  );

  revalidatePath("/cases");
  return { data: result[0] };
}

export async function updateCase(id: string, data: unknown) {
  const session = await auth();
  if (!session?.user || !["admin", "attorney"].includes(session.user.role as string)) {
    return { error: "Unauthorized" };
  }

  const validated = updateCaseSchema.safeParse(data);
  if (!validated.success) {
    return { error: validated.error.issues[0].message };
  }

  const { hourlyRate, flatFeeAmount, contingencyPercentage, estimatedValue, statuteOfLimitations, dateFiled, ...rest } = validated.data;

  const result = await db
    .update(cases)
    .set({
      ...rest,
      hourlyRate: hourlyRate !== undefined ? String(hourlyRate) : undefined,
      flatFeeAmount: flatFeeAmount !== undefined ? String(flatFeeAmount) : undefined,
      contingencyPercentage: contingencyPercentage !== undefined ? String(contingencyPercentage) : undefined,
      estimatedValue: estimatedValue !== undefined ? String(estimatedValue) : undefined,
      statuteOfLimitations: statuteOfLimitations ? new Date(statuteOfLimitations) : undefined,
      dateFiled: dateFiled ? new Date(dateFiled) : undefined,
      updatedAt: new Date(),
    })
    .where(eq(cases.id, id))
    .returning();

  if (validated.data.status) {
    await db.insert(caseTimeline).values({
      caseId: id,
      userId: session.user.id as string,
      eventType: "status_change",
      title: `Status changed to ${validated.data.status}`,
      isAutoGenerated: true,
    });
  }

  await createAuditLog(
    session.user.id as string,
    "update",
    "case",
    id,
    { updated: validated.data }
  );

  revalidatePath("/cases");
  revalidatePath(`/cases/${id}`);
  return { data: result[0] };
}

export async function addCaseNote(caseId: string, data: unknown) {
  const session = await auth();
  if (!session?.user || !["admin", "attorney"].includes(session.user.role as string)) {
    return { error: "Unauthorized" };
  }

  const validated = createCaseNoteSchema.safeParse(data);
  if (!validated.success) {
    return { error: validated.error.issues[0].message };
  }

  const result = await db
    .insert(caseNotes)
    .values({
      caseId,
      authorId: session.user.id as string,
      content: validated.data.content,
      isPrivate: validated.data.isPrivate,
    })
    .returning();

  revalidatePath(`/cases/${caseId}`);
  return { data: result[0] };
}

export async function addCaseParty(caseId: string, data: unknown) {
  const session = await auth();
  if (!session?.user || !["admin", "attorney"].includes(session.user.role as string)) {
    return { error: "Unauthorized" };
  }

  const validated = addCasePartySchema.safeParse(data);
  if (!validated.success) {
    return { error: validated.error.issues[0].message };
  }

  const result = await db
    .insert(caseParties)
    .values({
      caseId,
      ...validated.data,
    })
    .returning();

  revalidatePath(`/cases/${caseId}`);
  return { data: result[0] };
}

export async function assignCase(caseId: string, data: unknown) {
  const session = await auth();
  if (!session?.user || !["admin", "attorney"].includes(session.user.role as string)) {
    return { error: "Unauthorized" };
  }

  const validated = assignCaseSchema.safeParse(data);
  if (!validated.success) {
    return { error: validated.error.issues[0].message };
  }

  const result = await db
    .insert(caseAssignments)
    .values({
      caseId,
      userId: validated.data.userId,
      role: validated.data.role,
    })
    .returning();

  await db.insert(caseTimeline).values({
    caseId,
    userId: session.user.id as string,
    eventType: "assignment",
    title: `Attorney assigned (${validated.data.role})`,
    isAutoGenerated: true,
  });

  revalidatePath(`/cases/${caseId}`);
  return { data: result[0] };
}

export async function unassignCase(assignmentId: string, caseId: string) {
  const session = await auth();
  if (!session?.user || !["admin", "attorney"].includes(session.user.role as string)) {
    return { error: "Unauthorized" };
  }

  await db
    .update(caseAssignments)
    .set({ unassignedAt: new Date() })
    .where(eq(caseAssignments.id, assignmentId));

  revalidatePath(`/cases/${caseId}`);
  return { success: true };
}

export async function updateCasePipelineStage(caseId: string, stageId: string) {
  const session = await auth();
  if (!session?.user || !["admin", "attorney"].includes(session.user.role as string)) {
    return { error: "Unauthorized" };
  }

  await db
    .update(cases)
    .set({ pipelineStageId: stageId, updatedAt: new Date() })
    .where(eq(cases.id, caseId));

  revalidatePath("/cases");
  revalidatePath("/cases/pipeline");
  return { success: true };
}
