"use server";

import { db } from "@/lib/db";
import { cases, caseAssignments, caseNotes, caseTimeline, caseParties, pipelineStages } from "@/lib/db/schema/cases";
import { auth } from "@/lib/auth/auth";
import { createAuditLog } from "@/lib/utils/audit";
import { createCaseSchema, updateCaseSchema, createCaseNoteSchema, addCasePartySchema, assignCaseSchema } from "@/lib/validators/case";
import { generateCaseNumber } from "@/lib/queries/cases";
import { and, eq, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { safeAction } from "@/lib/utils/safe-action";
import { withUniqueRetry } from "@/lib/utils/with-retry";

async function isAssignedToCase(userId: string, caseId: string): Promise<boolean> {
  const [assignment] = await db
    .select({ id: caseAssignments.id })
    .from(caseAssignments)
    .where(and(
      eq(caseAssignments.caseId, caseId),
      eq(caseAssignments.userId, userId),
      sql`${caseAssignments.unassignedAt} IS NULL`
    ))
    .limit(1);
  return !!assignment;
}

export async function createCase(data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    const validated = createCaseSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const { hourlyRate, flatFeeAmount, contingencyPercentage, estimatedValue, statuteOfLimitations, dateFiled, ...rest } = validated.data;

    // Retry on unique constraint violation (concurrent number generation race)
    const result = await withUniqueRetry(async () => {
      const caseNumber = await generateCaseNumber();
      return await db
        .insert(cases)
        .values({
          ...rest,
          caseNumber,
          hourlyRate: hourlyRate ? String(hourlyRate) : undefined,
          flatFeeAmount: flatFeeAmount ? String(flatFeeAmount) : undefined,
          contingencyPercentage: contingencyPercentage ? String(contingencyPercentage) : undefined,
          estimatedValue: estimatedValue ? String(estimatedValue) : undefined,
          statuteOfLimitations: statuteOfLimitations ? new Date(statuteOfLimitations) : undefined,
          dateFiled: dateFiled ? new Date(dateFiled) : undefined,
        })
        .returning();
    });

    await db.insert(caseTimeline).values({
      caseId: result[0].id,
      userId: session.user.id,
      eventType: "case_created",
      title: "Case created",
      description: `Case ${result[0].caseNumber} was created`,
      isAutoGenerated: true,
    });

    await createAuditLog(
      session.user.id,
      "create",
      "case",
      result[0].id,
      { caseNumber: result[0].caseNumber, ...validated.data }
    );

    revalidatePath("/cases");
    return { data: result[0] };
  });
}

export async function updateCase(id: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    if (session.user.role === "attorney") {
      const assigned = await isAssignedToCase(session.user.id, id);
      if (!assigned) return { error: "You are not assigned to this case" };
    }

    const validated = updateCaseSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const { hourlyRate, flatFeeAmount, contingencyPercentage, estimatedValue, statuteOfLimitations, dateFiled, ...rest } = validated.data;

    const result = await db
      .update(cases)
      .set({
        ...rest,
        hourlyRate: hourlyRate !== undefined ? String(hourlyRate) : undefined,
        flatFeeAmount: flatFeeAmount !== undefined ? String(flatFeeAmount) : undefined,
        contingencyPercentage: contingencyPercentage !== undefined ? String(contingencyPercentage) : undefined,
        estimatedValue: estimatedValue !== undefined ? String(estimatedValue) : undefined,
        statuteOfLimitations: statuteOfLimitations ? new Date(statuteOfLimitations) : undefined,
        dateFiled: dateFiled ? new Date(dateFiled) : undefined,
        updatedAt: new Date(),
      })
      .where(eq(cases.id, id))
      .returning();

    if (validated.data.status) {
      await db.insert(caseTimeline).values({
        caseId: id,
        userId: session.user.id,
        eventType: "status_change",
        title: `Status changed to ${validated.data.status}`,
        isAutoGenerated: true,
      });
    }

    await createAuditLog(
      session.user.id,
      "update",
      "case",
      id,
      { updated: validated.data }
    );

    revalidatePath("/cases");
    revalidatePath(`/cases/${id}`);
    return { data: result[0] };
  });
}

export async function addCaseNote(caseId: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    if (session.user.role === "attorney") {
      const assigned = await isAssignedToCase(session.user.id, caseId);
      if (!assigned) return { error: "You are not assigned to this case" };
    }

    const validated = createCaseNoteSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db
      .insert(caseNotes)
      .values({
        caseId,
        authorId: session.user.id,
        content: validated.data.content,
        isPrivate: validated.data.isPrivate,
      })
      .returning();

    revalidatePath(`/cases/${caseId}`);
    return { data: result[0] };
  });
}

export async function addCaseParty(caseId: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    if (session.user.role === "attorney") {
      const assigned = await isAssignedToCase(session.user.id, caseId);
      if (!assigned) return { error: "You are not assigned to this case" };
    }

    const validated = addCasePartySchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db
      .insert(caseParties)
      .values({
        caseId,
        ...validated.data,
      })
      .returning();

    revalidatePath(`/cases/${caseId}`);
    return { data: result[0] };
  });
}

export async function assignCase(caseId: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    const validated = assignCaseSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db
      .insert(caseAssignments)
      .values({
        caseId,
        userId: validated.data.userId,
        role: validated.data.role,
      })
      .returning();

    await db.insert(caseTimeline).values({
      caseId,
      userId: session.user.id,
      eventType: "assignment",
      title: `Attorney assigned (${validated.data.role})`,
      isAutoGenerated: true,
    });

    revalidatePath(`/cases/${caseId}`);
    return { data: result[0] };
  });
}

export async function unassignCase(assignmentId: string, caseId: string) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    // Verify assignment exists and belongs to the given case
    const [assignment] = await db
      .select({ id: caseAssignments.id })
      .from(caseAssignments)
      .where(and(eq(caseAssignments.id, assignmentId), eq(caseAssignments.caseId, caseId)))
      .limit(1);
    if (!assignment) return { error: "Assignment not found" };

    await db
      .update(caseAssignments)
      .set({ unassignedAt: new Date() })
      .where(eq(caseAssignments.id, assignmentId));

    revalidatePath(`/cases/${caseId}`);
    return { success: true };
  });
}

export async function updateCasePipelineStage(caseId: string, stageId: string) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || !["admin", "attorney"].includes(session.user.role)) {
      return { error: "Unauthorized" };
    }

    await db
      .update(cases)
      .set({ pipelineStageId: stageId, updatedAt: new Date() })
      .where(eq(cases.id, caseId));

    revalidatePath("/cases");
    revalidatePath("/cases/pipeline");
    return { success: true };
  });
}

// --- Pipeline Stages ---
const pipelineStageSchema = z.object({
  name: z.string().min(1, "Name is required"),
  description: z.string().optional(),
  order: z.number().int().min(0),
  color: z.string().optional(),
  isDefault: z.boolean().default(false),
});

export async function createPipelineStage(data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || session.user.role !== "admin") {
      return { error: "Unauthorized" };
    }

    const validated = pipelineStageSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    const result = await db.insert(pipelineStages).values(validated.data).returning();

    revalidatePath("/cases/pipeline");
    revalidatePath("/settings");
    return { data: result[0] };
  });
}

export async function updatePipelineStage(id: string, data: unknown) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || session.user.role !== "admin") {
      return { error: "Unauthorized" };
    }

    const validated = pipelineStageSchema.safeParse(data);
    if (!validated.success) {
      return { error: validated.error.issues[0].message };
    }

    await db.update(pipelineStages).set(validated.data).where(eq(pipelineStages.id, id));

    revalidatePath("/cases/pipeline");
    revalidatePath("/settings");
    return { success: true };
  });
}

export async function deletePipelineStage(id: string) {
  return safeAction(async () => {
    const session = await auth();
    if (!session?.user || session.user.role !== "admin") {
      return { error: "Unauthorized" };
    }

    await db.delete(pipelineStages).where(eq(pipelineStages.id, id));

    revalidatePath("/cases/pipeline");
    revalidatePath("/settings");
    return { success: true };
  });
}
