import { db } from "@/lib/db";
import { cases, caseAssignments, caseNotes, caseTimeline, caseParties, pipelineStages } from "@/lib/db/schema/cases";
import { clients } from "@/lib/db/schema/clients";
import { users } from "@/lib/db/schema/auth";
import { eq, ilike, or, and, sql, desc, asc } from "drizzle-orm";

interface CaseFilters {
  search?: string;
  status?: string;
  priority?: string;
  clientId?: string;
  assignedTo?: string;
  page?: number;
  limit?: number;
}

export async function getCases(filters: CaseFilters = {}) {
  const { search, status, priority, clientId, assignedTo, page = 1, limit = 20 } = filters;

  const conditions = [];
  if (status) conditions.push(eq(cases.status, status as "open" | "in_progress" | "hearing" | "resolved" | "closed" | "archived"));
  if (priority) conditions.push(eq(cases.priority, priority as "low" | "medium" | "high" | "urgent"));
  if (clientId) conditions.push(eq(cases.clientId, clientId));

  if (search) {
    conditions.push(
      or(
        ilike(cases.title, `%${search}%`),
        ilike(cases.caseNumber, `%${search}%`),
        ilike(cases.opposingParty, `%${search}%`)
      )
    );
  }

  let query = db
    .select({
      id: cases.id,
      caseNumber: cases.caseNumber,
      title: cases.title,
      status: cases.status,
      priority: cases.priority,
      caseType: cases.caseType,
      billingType: cases.billingType,
      clientName: sql<string>`${clients.firstName} || ' ' || ${clients.lastName}`,
      clientId: cases.clientId,
      createdAt: cases.createdAt,
    })
    .from(cases)
    .innerJoin(clients, eq(cases.clientId, clients.id))
    .where(conditions.length > 0 ? and(...conditions) : undefined)
    .orderBy(desc(cases.createdAt))
    .limit(limit)
    .offset((page - 1) * limit);

  const result = await query;

  const countResult = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(cases)
    .where(conditions.length > 0 ? and(...conditions) : undefined);

  return {
    data: result,
    total: countResult[0]?.count ?? 0,
    page,
    limit,
  };
}

export async function getCaseById(id: string) {
  const result = await db
    .select({
      id: cases.id,
      caseNumber: cases.caseNumber,
      title: cases.title,
      status: cases.status,
      priority: cases.priority,
      caseType: cases.caseType,
      practiceArea: cases.practiceArea,
      billingType: cases.billingType,
      hourlyRate: cases.hourlyRate,
      flatFeeAmount: cases.flatFeeAmount,
      contingencyPercentage: cases.contingencyPercentage,
      courtName: cases.courtName,
      courtCaseNumber: cases.courtCaseNumber,
      judge: cases.judge,
      opposingCounsel: cases.opposingCounsel,
      opposingParty: cases.opposingParty,
      statuteOfLimitations: cases.statuteOfLimitations,
      dateFiled: cases.dateFiled,
      estimatedValue: cases.estimatedValue,
      description: cases.description,
      notes: cases.notes,
      clientId: cases.clientId,
      clientName: sql<string>`${clients.firstName} || ' ' || ${clients.lastName}`,
      createdAt: cases.createdAt,
      updatedAt: cases.updatedAt,
    })
    .from(cases)
    .innerJoin(clients, eq(cases.clientId, clients.id))
    .where(eq(cases.id, id))
    .limit(1);

  return result[0] ?? null;
}

export async function getCaseAssignments(caseId: string) {
  return db
    .select({
      id: caseAssignments.id,
      role: caseAssignments.role,
      assignedAt: caseAssignments.assignedAt,
      userName: users.name,
      userId: caseAssignments.userId,
    })
    .from(caseAssignments)
    .innerJoin(users, eq(caseAssignments.userId, users.id))
    .where(eq(caseAssignments.caseId, caseId))
    .orderBy(asc(caseAssignments.assignedAt));
}

export async function getCaseNotes(caseId: string) {
  return db
    .select({
      id: caseNotes.id,
      content: caseNotes.content,
      isPrivate: caseNotes.isPrivate,
      createdAt: caseNotes.createdAt,
      authorName: users.name,
    })
    .from(caseNotes)
    .innerJoin(users, eq(caseNotes.authorId, users.id))
    .where(eq(caseNotes.caseId, caseId))
    .orderBy(desc(caseNotes.createdAt));
}

export async function getCaseTimeline(caseId: string) {
  return db
    .select({
      id: caseTimeline.id,
      eventType: caseTimeline.eventType,
      title: caseTimeline.title,
      description: caseTimeline.description,
      isAutoGenerated: caseTimeline.isAutoGenerated,
      createdAt: caseTimeline.createdAt,
      userName: users.name,
    })
    .from(caseTimeline)
    .leftJoin(users, eq(caseTimeline.userId, users.id))
    .where(eq(caseTimeline.caseId, caseId))
    .orderBy(desc(caseTimeline.createdAt));
}

export async function getCaseParties(caseId: string) {
  return db
    .select()
    .from(caseParties)
    .where(eq(caseParties.caseId, caseId))
    .orderBy(asc(caseParties.createdAt));
}

export async function getPipelineStages() {
  return db
    .select()
    .from(pipelineStages)
    .orderBy(asc(pipelineStages.order));
}

export async function getCasesByPipelineStage() {
  const stages = await getPipelineStages();
  const allCases = await db
    .select({
      id: cases.id,
      caseNumber: cases.caseNumber,
      title: cases.title,
      status: cases.status,
      priority: cases.priority,
      pipelineStageId: cases.pipelineStageId,
      clientName: sql<string>`${clients.firstName} || ' ' || ${clients.lastName}`,
    })
    .from(cases)
    .innerJoin(clients, eq(cases.clientId, clients.id))
    .where(
      or(
        eq(cases.status, "open"),
        eq(cases.status, "in_progress"),
        eq(cases.status, "hearing")
      )
    );

  return stages.map((stage) => ({
    ...stage,
    cases: allCases.filter((c) => c.pipelineStageId === stage.id),
  }));
}

export async function generateCaseNumber(): Promise<string> {
  const year = new Date().getFullYear();
  const result = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(cases);
  const num = (result[0]?.count ?? 0) + 1;
  return `CASE-${year}-${String(num).padStart(4, "0")}`;
}
