export const userData = {
  admin: {
    name: "John Kamau",
    email: "admin@lawfirm.co.ke",
    role: "admin" as const,
    phone: "+254700000001",
  },
  attorneys: [
    {
      user: {
        name: "Jane Wanjiku",
        email: "attorney1@lawfirm.co.ke",
        role: "attorney" as const,
        phone: "+254700000002",
      },
      attorney: {
        barNumber: "ADV/2010/54321",
        jurisdiction: "Kenya",
        title: "partner" as const,
        department: "Litigation",
        hourlyRate: "15000",
        dateAdmitted: new Date("2010-06-15"),
        bio: "Senior Partner with 15+ years experience in civil and commercial litigation.",
        lskNumber: "LSK/2010/54321",
        commissionerForOaths: true,
        notaryPublic: true,
        seniorCounsel: false,
      },
      practisingCertificates: [
        {
          year: "2025",
          certificateNumber: "PC/2025/54321",
          issueDate: new Date("2025-01-15"),
          expiryDate: new Date("2025-12-31"),
          status: "active" as const,
        },
        {
          year: "2026",
          certificateNumber: "PC/2026/54321",
          issueDate: new Date("2026-01-10"),
          expiryDate: new Date("2026-12-31"),
          status: "active" as const,
        },
      ],
      cpdRecords: [
        {
          title: "LSK Annual Conference 2025",
          provider: "Law Society of Kenya",
          units: "5",
          completionDate: new Date("2025-08-20"),
          year: "2025",
        },
        {
          title: "AML/CFT Compliance Workshop",
          provider: "LSK Continuing Legal Education",
          units: "3",
          completionDate: new Date("2025-10-15"),
          year: "2025",
        },
      ],
    },
    {
      user: {
        name: "Peter Ochieng",
        email: "attorney2@lawfirm.co.ke",
        role: "attorney" as const,
        phone: "+254700000003",
      },
      attorney: {
        barNumber: "ADV/2015/12345",
        jurisdiction: "Kenya",
        title: "senior_associate" as const,
        department: "Corporate",
        hourlyRate: "10000",
        dateAdmitted: new Date("2015-03-20"),
        bio: "Corporate law specialist focusing on M&A, company formation, and commercial contracts.",
        lskNumber: "LSK/2015/12345",
        commissionerForOaths: true,
        notaryPublic: false,
        seniorCounsel: false,
      },
      practisingCertificates: [
        {
          year: "2026",
          certificateNumber: "PC/2026/12345",
          issueDate: new Date("2026-01-12"),
          expiryDate: new Date("2026-12-31"),
          status: "active" as const,
        },
      ],
      cpdRecords: [
        {
          title: "Corporate Governance Seminar",
          provider: "Institute of Certified Secretaries",
          units: "4",
          completionDate: new Date("2025-09-10"),
          year: "2025",
        },
      ],
    },
    {
      user: {
        name: "Mary Akinyi",
        email: "attorney3@lawfirm.co.ke",
        role: "attorney" as const,
        phone: "+254700000004",
      },
      attorney: {
        barNumber: "ADV/2020/67890",
        jurisdiction: "Kenya",
        title: "associate" as const,
        department: "Family Law",
        hourlyRate: "7500",
        dateAdmitted: new Date("2020-11-05"),
        bio: "Family law practitioner specializing in divorce, custody, and succession matters.",
        lskNumber: "LSK/2020/67890",
        commissionerForOaths: false,
        notaryPublic: false,
        seniorCounsel: false,
      },
      practisingCertificates: [
        {
          year: "2026",
          certificateNumber: "PC/2026/67890",
          issueDate: new Date("2026-01-08"),
          expiryDate: new Date("2026-12-31"),
          status: "active" as const,
        },
      ],
      cpdRecords: [
        {
          title: "Children's Rights & Family Law Update",
          provider: "FIDA Kenya",
          units: "3",
          completionDate: new Date("2025-11-22"),
          year: "2025",
        },
      ],
    },
  ],
  clients: [
    {
      user: {
        name: "David Mwangi",
        email: "client1@example.com",
        role: "client" as const,
        phone: "+254711000001",
      },
      client: {
        type: "individual" as const,
        firstName: "David",
        lastName: "Mwangi",
        email: "client1@example.com",
        phone: "+254711000001",
        county: "Nairobi",
        kraPin: "A001234567B",
        physicalAddress: "Westlands, Nairobi",
        poBox: "P.O. Box 12345-00100, Nairobi",
      },
    },
    {
      user: {
        name: "Sarah Njeri",
        email: "client2@example.com",
        role: "client" as const,
        phone: "+254711000002",
      },
      client: {
        type: "individual" as const,
        firstName: "Sarah",
        lastName: "Njeri",
        email: "client2@example.com",
        phone: "+254711000002",
        county: "Mombasa",
        kraPin: "A007654321C",
        physicalAddress: "Nyali, Mombasa",
        poBox: "P.O. Box 54321-80100, Mombasa",
      },
    },
  ],
};

export const sampleCases = [
  {
    caseNumber: "2026-0001",
    title: "Mwangi v. ABC Corporation Ltd — Employment Dispute",
    caseType: "Employment/Labour",
    practiceArea: "Employment/Labour",
    status: "in_progress" as const,
    priority: "high" as const,
    billingType: "hourly" as const,
    courtName: "Employment and Labour Relations Court",
    courtCaseNumber: "ELRC/E/001/2026",
    description: "Wrongful termination claim filed by client against former employer.",
    estimatedValue: "2500000",
  },
  {
    caseNumber: "2026-0002",
    title: "Njeri Family — Succession & Probate Matter",
    caseType: "Probate/Succession",
    practiceArea: "Probate/Succession",
    status: "open" as const,
    priority: "medium" as const,
    billingType: "flat_fee" as const,
    flatFeeAmount: "150000",
    courtName: "High Court of Kenya",
    courtCaseNumber: "SUCC/P/023/2026",
    description: "Administration of estate for deceased family member.",
    estimatedValue: "15000000",
  },
  {
    caseNumber: "2026-0003",
    title: "Mwangi Land Dispute — Kiambu Property",
    caseType: "Environment/Land",
    practiceArea: "Conveyancing/Property",
    status: "hearing" as const,
    priority: "high" as const,
    billingType: "hourly" as const,
    courtName: "Environment and Land Court (ELC)",
    courtCaseNumber: "ELC/002/2026",
    description: "Land boundary dispute over property in Kiambu County.",
    estimatedValue: "8000000",
  },
  {
    caseNumber: "2026-0004",
    title: "Njeri v. Landlord — Tenancy Dispute",
    caseType: "Civil Litigation",
    practiceArea: "Civil Litigation",
    status: "resolved" as const,
    priority: "low" as const,
    billingType: "flat_fee" as const,
    flatFeeAmount: "50000",
    courtName: "Magistrate Courts",
    description: "Rental deposit refund and illegal eviction claim.",
    estimatedValue: "500000",
  },
  {
    caseNumber: "2026-0005",
    title: "Mwangi Enterprises — Company Registration",
    caseType: "Corporate/Commercial",
    practiceArea: "Corporate/Commercial",
    status: "open" as const,
    priority: "medium" as const,
    billingType: "flat_fee" as const,
    flatFeeAmount: "75000",
    description: "New company registration and shareholder agreement drafting.",
  },
];
